### ISSUE TITLE
Fix outstanding errors

### ISSUE THREAD

**Issue by mike-ivs** [UoA-eResearch/SPOC-Rongowai-L1#28]
Here are several outstanding errors in the L1 backlog:

- [x] <class 'ValueError'> x and y arrays must be equal in length along interpolation axis.
- [x] <class 'ValueError'> math domain error
- [x] <class 'ValueError'> operands could not be broadcast together with shapes (XXX,) (YYY,) 
- [x] <class 'TypeError'> iteration over a 0-d array
- [x] <class 'ValueError'> One of the requested xi is out of bounds in dimension 0
- [x] shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (6,) and arg 1 with shape (9,).
- [x] <class 'TypeError'> 'tuple' object does not support item assignment

**Comment by mike-ivs** [comment]
caused by spontaneous "masked" values in 2D L0 data not already captured by attempted masking. very rare (3 files in 2 years).
```Traceback (most recent call last):
  File "SPOC-Rongowai-L1/sxs/L1_main.py", line 355, in <module>
    process_L1s(filepath, new_L1_file, inp, L1_DICT, settings)
  File "SPOC-Rongowai-L1/sxs/L1_main.py", line 33, in process_L1s
    L1 = L1_file(L1_filename, settings, L0, inp)
  File "SPOC-Rongowai-L1/sxs/output.py", line 28, in __init__
    self.interpolate_L0(L0, inp)
  File "SPOC-Rongowai-L1/sxs/output.py", line 226, in interpolate_L0
    self.postCal["add_range_to_sp"][:, ngrx_channel] = interp_ddm(
  File "SPOC-Rongowai-L1/sxs/utils.py", line 59, in interp_ddm
    interp_func = interp1d(x, y, kind="linear", fill_value="extrapolate")
  File ".virtualenvs/rongowai-L1/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 491, in __init__
    _Interpolator1D.__init__(self, x, y, axis=axis)
  File ".virtualenvs/rongowai-L1/lib/python3.10/site-packages/scipy/interpolate/_polyint.py", line 56, in __init__
    self._set_yi(yi, xi=xi, axis=axis)
  File ".virtualenvs/rongowai-L1/lib/python3.10/site-packages/scipy/interpolate/_polyint.py", line 126, in _set_yi
    raise ValueError("x and y arrays must be equal in length along "
ValueError: x and y arrays must be equal in length along interpolation axis.

**Comment by mike-ivs** [comment]
[22e6f5a](https://github.com/UoA-eResearch/SPOC-Rongowai-L1/commit/22e6f5aee90242c6e5a5a1adefe571ed9a6b90c6)

**Comment by mike-ivs** [comment]
Math domain error caused by poor satellite position/velocity/etc values (val<1e-300) from the GPS_GetSVInfo.cpp script.

**Comment by mike-ivs** [comment]
[1f68055](https://github.com/UoA-eResearch/SPOC-Rongowai-L1/commit/1f6805577755650274cc69769deb6d38ec1761f1)

**Comment by mike-ivs** [comment]
<class 'ValueError'> operands could not be broadcast together with shapes (XXX,) (YYY,)
 caused by spontaneous "masked" values in 1D L0 data not already captured by attempted masking. very rare (4 files in 2 years).

**Comment by mike-ivs** [comment]
3d776e6cdf50b0c4ac9b8e934e358d7f807985eb

**Comment by mike-ivs** [comment]
<class 'ValueError'> One of the requested xi is out of bounds in dimension 0

caused by point falling "outside" of the landmask/coast_dist file. Out of Bounds means ocean, so set to extrap/fill value of large negative

91a9c57d621e3adafbcae861550142a520aba06e

**Comment by mike-ivs** [comment]
shape mismatch: objects cannot be broadcast to a single shape. Mismatch is between arg 0 with shape (6,) and arg 1 with shape (9,).

Caused by "edge of DEM" issues with local DEM slice.

6aa5efcdc39714a912154f0f370f15dff8de5cb8

**Comment by mike-ivs** [comment]
<class 'TypeError'> 'tuple' object does not support item assignment
f12d050bac6b78bae907c5e449f4f2234c307ae8

**Comment by mike-ivs** [comment]
[0851535](https://github.com/UoA-eResearch/SPOC-Rongowai-L1/commit/0851535d175c4c7a7c8e8b9b1ae92cf2216eb428)
